Correct several issues with selection ranges.
nathanfaucett/svelte-slate pull request #9
Opened 2023-04-20 15:55 UTC by twig1337

I found that selecting blocks was pretty buggy on Chrome. When poking around I discovered several assumptions that were causing the selections to get randomly removed and corrected them. I'm confident there are more issues out there but I haven't had a chance to dig deeper yet.

2023-05-22 19:12 UTC, nathanfaucett requested changes
Sorry for taking so long to look at this

2023-05-22 19:12 UTC, nathanfaucett commented on src/lib/plugins/ImageElement.svelte
> +		editor.isVoid = element => {
i think this should be moved to the `withImage` of the Image plugin

2023-05-22 19:12 UTC, merged

2023-05-22 19:15 UTC, twig1337 commented
@nathanfaucett No worries man! And I apologize if I'm not dropping these changes in the right place. I'm relatively new to both Svelte and Slate so I'm sure I'll make some mistakes hahaha

2023-05-24 12:27 UTC, nathanfaucett commented
@twig1337 you put them in the right place, I noticed after I submitted the review, I deleted the comment, thanks for the fixes